#!/bin/bash

# View log for various VM/machines.
# Script uses Tmux.

tmux new-session -d
tmux split-window -d -t 0 -h

COMMANDS='sudo tail -f /var/log/syslog /var/log/*.log /var/log/dmesg'

SAMIRCOMMAND="ssh samir -t $COMMANDS"
DADARCOMMAND="ssh dadarv6 -t $COMMANDS"

tmux send-keys -t 0 "$COMMANDS" enter
tmux send-keys -t 1 "$SAMIRCOMMAND" enter

tmux select-pane -t 0

tmux rename  syslog_viewer
tmux attach
