#!/bin/bash

# Script for updating several machines by calling 'apt-get update && apt-get upgrade'.
# Script for setting up Tmux.

tmux new-session -d
tmux split-window -d -t 0 -h

COMMANDS='sudo apt-get update && sudo apt-get upgrade'

tmux send-keys -t 0 "$COMMANDS" enter
tmux send-keys -t 1 'ssh samir -t "sudo apt-get update && sudo apt-get upgrade"' enter

tmux select-pane -t 0

tmux rename  upgrade_all
tmux attach
